### ISSUE TITLE
Change isoband maintainership

### ISSUE THREAD

**Issue by clauswilke** [r-lib/isoband#36]
As I've mentioned in the past, I think it would make sense for Posit to have formal maintainership of isoband, due to isoband's importance in the ggplot2 stack. I'd like to emphasize that I've long thought this is a good strategy going forward, and I'm not in any way wanting to step down because I'm angry or upset. I am much better at building new tools than I am at long-term maintainership, so this is a logical evolution for the package.

@hadley @thomasp85 Please let me know who you think the next maintainer should be. Thanks!

**Comment by thomasp85** [comment]
It should probably be me🙂

**Comment by hadley** [comment]
@clauswilke do you want to start by transferring to r-lib?

**Comment by clauswilke** [comment]
@hadley Happy to do that, but can I? I frequently want to move personal repos of my students to wilkelab and usually the process is that they have to first transfer to my personal account and then I can transfer to wilkelab, because they don't have the permission to create new repos under wilkelab. I assume the situation here would be the same. Do you want me to try and see what happens?

**Comment by hadley** [comment]
I think you just do it, and then it sends me a request which I then confirm.

**Comment by clauswilke** [comment]
Just tried. This is the error I always get:
<img width="545" alt="Screen Shot 2022-12-11 at 3 43 29 PM" src="https://user-images.githubusercontent.com/4210929/206930509-775ea9ae-54f8-47e1-a48a-54a3fcd7c618.png">

I could transfer to @hadley, and then you transfer to r-lib.

**Comment by hadley** [comment]
Hmm weird, I guess I've never encountered how broken this workflow is. But yeah, transferring to me first is fine.

**Comment by clauswilke** [comment]
It's even crazier than that. I have to transfer to myself first. 
<img width="749" alt="Screen Shot 2022-12-12 at 11 01 03 PM" src="https://user-images.githubusercontent.com/4210929/207230891-00ed3feb-73f4-4b51-a51a-b7dd31bec3b8.png">

**Comment by hadley** [comment]
Crazy! Should be in r-lib momentarily.

**Comment by hadley** [comment]
I'll submit to CRAN later today (once the subdomain is live). @clauswilke Let me know if there's anything we can do to better credit you to as the real creator of the package.

**Comment by clauswilke** [comment]
@hadley Maybe mention in the changelog that maintainership was changed after the original author (Claus Wilke) donated code base to r-lib? In this way it's formally recorded somewhere. I don't need more credit than that.

Also, website is live but creates a certificate warning for now.

**Comment by hadley** [comment]
I _think_ the certificate issue will naturally resolve itself. 

I'll add some wording to that effect to the readme and the DESCRIPTION.

**Comment by clauswilke** [comment]
Certificate issue looks resolved now.

**Comment by hadley** [comment]
Thanks! I'll submit shortly
